# Generated by Django 4.1.2 on 2022-12-03 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name of the income')),
                ('value', models.DecimalField(decimal_places=2, max_digits=32, max_length=40, verbose_name='Value of the income')),
                ('typeincome', models.CharField(choices=[('Monthly', 'Monthly'), ('Period', 'Period'), ('Extra', 'Extra')], max_length=30, verbose_name='Type of the income')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='money.categoryincome', verbose_name='Category of the income')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name of the expense')),
                ('value', models.DecimalField(decimal_places=2, max_digits=32, max_length=40, verbose_name='Value of the expense')),
                ('typeexpense', models.CharField(choices=[('Monthly', 'Monthly'), ('Period', 'Period'), ('Extra', 'Extra'), ('Day by day', 'Day by day')], max_length=30, verbose_name='Type of the expense')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='money.categoryexpense', verbose_name='Category of the expense')),
            ],
        ),
    ]
